"""Plot the line experiments generated by run_line.sh."""
import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.colors import LogNorm, TwoSlopeNorm
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "artifacts" / "line"
OUT = ROOT / "evidence"
OUT.mkdir(exist_ok=True)


def read(name):
    return json.loads((DATA / name).read_text())


def stability(z):
    return abs(1 + z + z*z/2 + z*z*z/6 + z*z*z*z/24)


def draw_stability():
    count = 241
    re = np.linspace(-4, 1, count)
    im = np.linspace(-3.5, 3.5, count)
    xx, yy = np.meshgrid(re, im)
    growth = np.array(read("growth-map.json")).reshape(count, count)
    z = xx + 1j*yy
    fig, axs = plt.subplots(1, 3, figsize=(15, 4.7), constrained_layout=True)
    ax = axs[0]
    image = ax.pcolormesh(xx, yy, growth, shading="auto", norm=LogNorm(vmin=0.03, vmax=20), cmap="coolwarm")
    fig.colorbar(image, ax=ax, label="measured growth factor |y₁/y₀|")
    ax.contour(xx, yy, stability(z), [1], colors="black", linewidths=1.8)
    ax.contour(xx, yy, abs(1+z), [1], colors="white", linestyles="--", linewidths=1.1)
    ax.contour(xx, yy, abs(1+z+z*z/2), [1], colors="yellow", linestyles="--", linewidths=1.1)
    k = np.arange(-32, 32)
    for h, color in [(0.045, "#09a66b"), (0.056, "#3b1a9a")]:
        lam = -0.05*k*k - 1j*np.where(k == -32, 0, k)
        if h == 0.045:
            assert np.max(stability(lam*h)) <= 1 + 1e-12
        else:
            assert np.max(stability(lam*h)) > 1
        ax.scatter((lam*h).real, (lam*h).imag, s=10, color=color, alpha=.65, label=f"line modes Δt={h}")
    ax.set(xlim=(-4, 1), ylim=(-3.5, 3.5), xlabel="Re(z)", ylabel="Im(z)", title="RK4 stability: measured growth")
    ax.legend(fontsize=7, loc="upper right")
    for ax, name, h in zip(axs[1:], ["stable.json", "unstable.json"], [0.045, 0.056]):
        run = read(name)
        frames = np.asarray(run["profiles"])
        ax.imshow(frames, origin="upper", aspect="auto", cmap="RdBu_r", extent=[0, 2*np.pi, run["times"][-1], 0], vmin=-1.5, vmax=1.5)
        ax.set(xlabel="x", ylabel="time t", title=f"Gaussian pulse, RK4 Δt={h}")
    fig.savefig(OUT / "line-stability.png", dpi=180)
    plt.close(fig)


def draw_accuracy():
    fig, axs = plt.subplots(1, 2, figsize=(12, 4.5), constrained_layout=True)
    exact = read("pulse-fourier.json")
    axs[0].plot(exact["x"], exact["exact"], "k--", lw=2, label="exact")
    for name, label in [("pulse-fourier.json", "RK4, Fourier"), ("pulse-centred.json", "RK4, centred differences"), ("pulse-euler.json", "Euler, Fourier")]:
        run = read(name)
        axs[0].plot(run["x"], run["u"], label=f"{label} (err={run['max_error']:.3g})")
        print(label, "maximum error", run["max_error"])
    axs[0].set(xlabel="x", ylabel="u(x, t)", title="Pulse after one lap")
    axs[0].legend(fontsize=8)
    h = np.array([.02, .01, .005, .0025])
    for method, label in [("euler", "Euler"), ("rk2", "midpoint"), ("rk4", "RK4"), ("rk4-equal", "equal-weight RK4")]:
        errors = np.array([read(f"error-{method}-{dt}.json")["max_error"] for dt in ["0.02", "0.01", "0.005", "0.0025"]])
        slope = np.polyfit(np.log(h), np.log(errors), 1)[0]
        expected = {"euler": 1, "rk2": 2, "rk4": 4, "rk4-equal": 2}[method]
        assert abs(slope - expected)/expected < .15, (method, slope)
        axs[1].loglog(h, errors, "o-", label=f"{label}, slope {slope:.2f}")
        print(label, "slope", slope)
    axs[1].set(xlabel="time step Δt", ylabel="maximum error at t=1", title="Time-step accuracy")
    axs[1].legend(fontsize=8)
    axs[1].grid(True, which="both", alpha=.25)
    fig.savefig(OUT / "line-accuracy.png", dpi=180)
    plt.close(fig)


if __name__ == "__main__":
    draw_stability()
    draw_accuracy()
